#!/bin/sh
# Shared helpers for the mosquitto native process-based run skill.
# POSIX sh only (macOS /bin/sh and Linux dash/bash). No bashisms.
#
# Sourced by every script in scripts/. Provides: workspace paths, ports,
# state helpers (via state.py), liveness checks, log helpers and readiness waits.

set -u

# Portable short delay: BSD/GNU sleep accept fractions; busybox does not.
SLEEP_TICK=0.1
if ! sleep 0.1 2>/dev/null; then SLEEP_TICK=1; fi

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
RUN_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd -P)
AGENTS_DIR=$(CDPATH= cd -- "$RUN_DIR/../.." && pwd -P)
REPO_ROOT=$(CDPATH= cd -- "$AGENTS_DIR/.." && pwd -P)
MOSQ_ROOT="$REPO_ROOT/mosquitto"

RUNTIME_DIR="$AGENTS_DIR/runtime"
STATE_FILE="${RUN_STATE_FILE:-$RUNTIME_DIR/processes.json}"
LOG_DIR="$RUNTIME_DIR/logs"
STATE_PY="$SCRIPT_DIR/state.py"

BUILD_DIR="${MOSQ_BUILD_DIR:-$MOSQ_ROOT/build}"
MOSQ_BIN="$BUILD_DIR/src/mosquitto"
MOSQ_CONF="$RUNTIME_DIR/mosquitto.conf"

MOSQ_PORT="${MOSQ_PORT:-1883}"
DASHBOARD_PORT="${DASHBOARD_PORT:-3000}"
DASHBOARD_DIR="$MOSQ_ROOT/dashboard/src"
PY="${PYTHON:-python3}"

export RUN_STATE_FILE="$STATE_FILE"

ensure_dirs() {
    mkdir -p "$RUNTIME_DIR" "$LOG_DIR"
}

state_set() { # name pid logPath workdir command port
    "$PY" "$STATE_PY" set "$@"
}

state_remove() { # name
    "$PY" "$STATE_PY" remove "$1"
}

state_field() { # name field  -> value or empty
    "$PY" "$STATE_PY" field "$1" "$2" 2>/dev/null || true
}

state_names() {
    "$PY" "$STATE_PY" names
}

state_uptime() { # epoch -> HH:MM:SS
    "$PY" "$STATE_PY" uptime "$1"
}

is_alive() { # pid
    [ -n "${1:-}" ] && kill -0 "$1" 2>/dev/null
}

normalize_pids() { # pid...  -> unique, space separated, empties dropped
    for _p in "$@"; do
        [ -n "$_p" ] && printf '%s\n' "$_p"
    done | sort -u | tr '\n' ' '
}

app_pid() { # name
    state_field "$1" pid
}

app_is_alive() { # name
    is_alive "$(app_pid "$1")"
}

new_log_path() { # app
    ensure_dirs
    printf '%s/%s.%s.txt\n' "$LOG_DIR" "$1" "$(date +%Y%m%d-%H%M%S)"
}

last_log_line() { # path
    if [ -f "$1" ]; then
        tail -n 1 "$1" 2>/dev/null | tr -d '\r'
    else
        printf '<log file missing>'
    fi
}

port_listening() { # port
    if command -v lsof >/dev/null 2>&1; then
        lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1
    elif command -v nc >/dev/null 2>&1; then
        nc -z 127.0.0.1 "$1" >/dev/null 2>&1
    else
        return 1
    fi
}

http_ready() { # url
    command -v curl >/dev/null 2>&1 || return 1
    curl -fsS -o /dev/null --max-time 2 "$1" >/dev/null 2>&1
}

# Kill a set of pids: SIGTERM, wait up to ~5s, then SIGKILL stragglers.
stop_pids() { # pid...
    _ids=""
    for _p in "$@"; do
        [ -n "$_p" ] && _ids="$_ids $_p"
    done
    [ -z "$_ids" ] && return 0
    for _p in $_ids; do is_alive "$_p" && kill -TERM "$_p" 2>/dev/null || true; done
    _deadline=$(( $(date +%s) + 5 ))
    while [ "$(date +%s)" -lt "$_deadline" ]; do
        _alive=""
        for _p in $_ids; do is_alive "$_p" && _alive="$_alive $_p"; done
        [ -z "$_alive" ] && return 0
        sleep "$SLEEP_TICK"
    done
    for _p in $_ids; do is_alive "$_p" && kill -KILL "$_p" 2>/dev/null || true; done
    sleep "$SLEEP_TICK"
}

# Print PIDs of project-related processes not tracked in state (orphans).
orphan_pids() { # name
    case "$1" in
        broker) _pat="$MOSQ_BIN|mosquitto -c $MOSQ_CONF|mosquitto -c" ;;
        dashboard) _pat="http.server $DASHBOARD_PORT" ;;
        *) return 0 ;;
    esac
    ps -axo pid=,args= 2>/dev/null | grep -E "$_pat" | grep -v grep | awk '{print $1}'
}

print_process_snapshot() {
    printf 'Native process snapshot (mosquitto/python):\n'
    _rows=$(ps -axo pid=,args= 2>/dev/null \
        | grep -E 'mosquitto|http\.server' | grep -v grep || true)
    if [ -z "$_rows" ]; then
        printf 'none\n'
        return 0
    fi
    printf '%s\n' "$_rows" | while read -r _pid _args; do
        case "$_args" in
            *"$MOSQ_BIN"*|*"http.server $DASHBOARD_PORT"*) _marker="MOSQ" ;;
            *) _marker="OTHER" ;;
        esac
        _args=$(printf '%s' "$_args" | cut -c1-200)
        printf '[%s] pid=%s\n' "$_marker" "$_pid"
        printf 'cmd: %s\n\n' "$_args"
    done
}

write_mosq_conf() {
    ensure_dirs
    cat > "$MOSQ_CONF" <<EOF
# Generated by .agents/skills/run — do not edit by hand.
listener $MOSQ_PORT 127.0.0.1
allow_anonymous true
persistence false
log_dest stdout
EOF
}

require_broker_binary() {
    if [ ! -x "$MOSQ_BIN" ]; then
        printf 'error: broker binary not found at %s\n' "$MOSQ_BIN" >&2
        printf 'build it first: %s/restart-after-build.sh broker\n' "$SCRIPT_DIR" >&2
        return 3
    fi
}
